name: DevOps App CI

on:
  push:
    branch:
      - master
  pull_request:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repositary
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build application and Nginx images
        run: docker compose build

      - name: Start application stack
        run: docker compose -f compose.yaml -f compose.ci.yaml up -d

      - name: Check container status
        run: docker compose -f compose.yaml -f compose.ci.yaml ps

      - name: Test application health
        run: curl --fail http://127.0.0.1/health

      - name: Test database health
        run: curl --fail http://127.0.0.1/db-health

      - name: Show logs
        if: always()
        run: docker compose -f compose.yaml -f compose.ci.yaml logs
