name: DevOps App CI

on:
  push:
    branch:
      - master
  pull_request:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositary
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build application image
        run: docker compose build app

      - name: Build Nginx image
        run: docker compose build nginx
